functionsDirectory = "c:\\Users\\Thamo\\Downloads\\chimpro-logsampling-ready\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "c:\\Users\\Thamo\\Downloads\\chimpro-logsampling-ready"
publishOrigin = "config"
functions = "c:\\Users\\Thamo\\Downloads\\chimpro-logsampling-ready\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[dev]
functionsPort = 9999

[scheduled]

  [[scheduled.functions]]
  function = "dailyNotify"
  cron = "0 0 * * *"

[functions]

  [functions."*"]